import React from 'react';
import Head from 'next/head';

interface CustomHeadProps {
  title: string;
  description?: string;
}

const CustomHead = ({title, description}: CustomHeadProps) => {
  return (
    <Head>
      <title>{title}</title>
      <meta
        name="description"
        content={description ? description : 'Generated by create next app'}
      />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default CustomHead;
